spring.application.name=auth-service

spring.datasource.username=root
spring.datasource.password=ayushgupta#cs22
spring.datasource.url=jdbc:mysql://localhost:3306/qma_user_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false